# Generated by Django 3.2.9 on 2021-11-18 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('konta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tytul', models.CharField(max_length=150, null=True)),
                ('tresc', models.TextField()),
                ('data_utw', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
