# Generated by Django 3.2.9 on 2021-11-21 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('konta', '0003_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
