# Generated by Django 3.2.9 on 2021-11-22 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('konta', '0005_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
