# Generated by Django 3.2.9 on 2021-11-26 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('konta', '0008_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['date_added']},
        ),
    ]
