# Generated by Django 3.2.9 on 2021-11-28 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('konta', '0013_auto_20211128_1328'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
